### ISSUE TITLE
The Webhook of commercejs return 404 error

### ISSUE THREAD

**Issue by sasuke0601** [chec/commerce-js-shopify-order-sync#1]
Hi, there.

I deployed forked repo on Netlify. But Webhook returns `404` error.
My setting: 
https://prnt.sc/ZfPQjfHL56va
https://prnt.sc/y8rGuDVLZWBH
https://prnt.sc/f1xtROGEdHXH
https://prnt.sc/pdIrjdd9W-w7

Please help me. 
Thanks.

**Comment by kvisca** [comment]
Hi there, I believe you meant to open an issue with Commerce.js so I will be closing this. I was unable to replicate any issue with the webhooks endpoint using Commerce.js.

If you believe this is an issue still, please open an issue in the [Commerce.js repo](https://github.com/chec/commerce.js).
